version: "3.3"
services:
  react-app-test:
    image: client-test
    build: ./client
    restart: "unless-stopped"
    ports:
      - "3000:3000"
    depends_on:
      - api-server-test
      # - mongo
    networks:
      - amotius-app-bridge-test
    command: "start"
  api-server-test:
    image: server-test
    build: .
    ports:
      - "4001:4000"
    networks:
      - amotius-app-bridge-test
    # depends_on:
    #   - mongo
    command: "start"
  # mongo:
  #   image: "mongo"
  #   container_name: mongo
  #   ports:
  #     - 27018:27017
  #   networks:
  #     - amotius-app-bridge
  #   volumes:
  #     - mongo-data:/data/db
  # cypress:
  #   image: cypress
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile.cypress
  #   environment:
  #     - CYPRESS_baseUrl=http://api-server:4000/api/
  #   networks:
  #     - amotius-app-bridge
  #   depends_on:
  #     - api-server
  #   command: npx cypress run
networks:
  amotius-app-bridge-test:
    driver: bridge
# volumes:
#   mongo-data:
#     driver: local
